### ISSUE TITLE
Autocomplete not working properly?

### ISSUE THREAD

**Issue by DarthIwan** [fr1zle/vscode-elixir#55] opened 2017-03-07 20:44 UTC
Hi there, 

first of all, thanks for this extension. I like Code very much and was happy to see an extension for Elixir for it.

Unfortunately I have some trouble to use it. I'm not sure if it's just me, or something is not working properly. But if I begin to type a word and Intellisense shows up (example def/2) and I press the Tab or Enter all I get is really the def/2 in the editor. Is it on purpose? I've used Atom for Elixir before and it also shows def/2, but after Tab I always got my clean:

def Name do

end

What do I wrong?

Best

**Comment by fr1zle** [comment] 2017-03-08 08:07
I think this is an old bug (#22) but this should be fixed in 0.1.1. Are running the latest version? 

I currently can't reproduce this on master, I will push out a new build once we have transitioned the rights to publish to me.

**Comment by philipgiuliani** [comment] 2017-03-08 18:52
I also have this bug in version 0.1.1.

![bug](https://cloud.githubusercontent.com/assets/5446019/23718677/ba9e813c-0438-11e7-8686-212dcaa80660.gif)

```bash
$ elixir -v
Erlang/OTP 19 [erts-8.2.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
Elixir 1.4.2
```

**Comment by fr1zle** [comment] 2017-03-08 18:59
Thanks for the detailed report @philipgiuliani 

Appearently the fix for #22 wasn't yet published in 0.1.1

I will publish the update once @mat-mcloughlin and I figure out how to transfer ownership

**Comment by fr1zle** [comment] 2017-03-09 18:08
@philipgiuliani @DarthIwan I pushed a new update, can you confirm that this issue is fixed now?

**Comment by philipgiuliani** [comment] 2017-03-09 18:12
Just updated and works great! :)
Thank you very much!

**Comment by fr1zle** [comment] 2017-03-09 18:15
Thanks for your feedback :-)

**Closed by fr1zle** 2017-03-09 18:15 UTC
