### ISSUE TITLE
Autocomplete with `do`

### ISSUE THREAD

**Issue by xareelee** [fr1zle/vscode-elixir#64] opened 2017-05-09 08:15 UTC
When typing `do`, it shows an autocomplete list as following:

![screen shot 2017-05-09 at 16 11 57](https://cloud.githubusercontent.com/assets/804308/25841329/42efd940-34d2-11e7-9882-81cfb8d2a676.png)

The `do...end` snippet is not the first match on the list. Any following **tab** or **enter** instruction will autocomplete with the first match — `defoverridable`, which is not what I want.

It's really annoying to me. Is there any way to change the order in the autocomplete list?

**Comment by fr1zle** [comment] 2017-05-09 12:20
This seems to be a regression with the latest visual studio code update.
I am not sure, wether there is a way for an extenstion do mitgate this,

Will definately look into that though!

**Comment by fr1zle** [comment] 2017-05-09 13:10
Microsoft confirmed that this is a bug and it will be fixed in the next recovery build.

See 
https://github.com/Microsoft/vscode/issues/26182
https://github.com/Microsoft/vscode/issues/26306

**Closed by fr1zle** 2017-05-09 13:10 UTC

**Comment by stuartbain** [comment] 2017-05-10 12:07
Add the following line to your VSCode preferences to fix this in the current version:
`"editor.snippetSuggestions": "inline"`
